### ISSUE TITLE
在update时，遇到报错，提示连接不上

### ISSUE THREAD

**Issue by XiaoZhaoxiaaa** [whyour/issue-blog#106]
下面是报错信息
![image](https://user-images.githubusercontent.com/32087837/79070685-08436180-7d0a-11ea-82df-2c6f7577f9e9.png)

**Comment by whyour** [comment]
> 下面是报错信息
> ![image](https://user-images.githubusercontent.com/32087837/79070685-08436180-7d0a-11ea-82df-2c6f7577f9e9.png)

是一直报错吗，还是有时报错，这看样子是请求api失败了

**Comment by whyour** [comment]
@XiaoZhaoxiaaa  如果有代理可以让github走代理，没有可以设置下github域名指向 `192.30.253.117 api.github.com`
