### ISSUE TITLE
get issues 有辦法用 vscode 打開嗎？

### ISSUE THREAD

**Issue by medophin** [whyour/issue-blog#174]
想請教 get issues 有辦法選擇用 vscode 打開成純文字嗎？

**Comment by whyour** [comment]
> 想請教 get issues 有辦法選擇用 vscode 打開成純文字嗎？

意思是单个 issue 在 vsocde 中打开为单个文件？

**Comment by whyour** [comment]
vscode.workspace.openTextDocument 这个api应该可以满足你的需求
![image](https://user-images.githubusercontent.com/22700758/91272545-79ae1900-e7ae-11ea-937d-c3c2b058f2dd.png)
https://code.visualstudio.com/api/references/vscode-api#workspace
